# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.

In [1]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if mode == "zeros":
        return np.zeros(shape)
    elif mode == "ones":
        return np.ones(shape)
    elif mode == "full":
        if value is None:
            raise ValueError("'full' mode requires a 'value' argument.")
        return np.full(shape, value)
    elif mode == "identity":
        # 'shape' is expected to be a single integer (size of the square matrix)
        if isinstance(shape, tuple):
            if shape[0] != shape[1]:
                raise ValueError("Identity matrix must be square (rows == cols).")
            size = shape[0]
        else:
            size = shape
        return np.identity(size)
    else:
        raise ValueError(f"Unknown mode: '{mode}'. Use 'zeros', 'ones', 'full', or 'identity'.")

**Test: `array_factory`**

In [2]:
print("zeros (2,3):\n", array_factory("zeros", (2, 3)))
print("\nones (3,2):\n", array_factory("ones", (3, 2)))
print("\nfull (2,2) value=7:\n", array_factory("full", (2, 2), value=7))
print("\nidentity size=4:\n", array_factory("identity", 4))

zeros (2,3):
 [[0. 0. 0.]
 [0. 0. 0.]]

ones (3,2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

full (2,2) value=7:
 [[7 7]
 [7 7]]

identity size=4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [3]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to ndarray to ensure they are processed as Tensors
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Rule: Change the shape of arr1 to new_shape
        # Common usage: turning a vector (1D) into a matrix (2D) by using reshape function
        reshaped_arr1 = arr1.reshape(new_shape)

        # Rule: Vertical Stacking (vstack)
        # Requirement: Both matrices must have the same number of columns
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")

**Test: `secure_reshape_and_stack`**

In [4]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6]

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9],
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print(final_report)
# Resulting shape: (4, 3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Test: mismatched column error handling**

In [5]:
# This should raise a "Company-grade Error" because column counts won't match (3 vs 4)
try:
    secure_reshape_and_stack(branch_a, branch_b, (3, 2))
except ValueError as e:
    print("Caught expected error:", e)

Caught expected error: Company-grade Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [6]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold)
    and replaces them with a new value.
    """
    # 1. Convert input to a numpy array (ndarray)
    arr = np.array(arr)

    # 2. Define the condition: elementwise comparison
    # This creates a Boolean numpy array
    condition = arr >= threshold

    # 3. Apply Modification using np.where()
    # np.where(condition, value_if_true, value_if_false)
    modified_arr = np.where(condition, replacement_value, arr)

    return modified_arr

### TestCase

In [7]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6]

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9],
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print(final_report)
# Resulting shape: (4, 3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
v = np.array([1, 2, 3])
apply_threshold(v, 2, -20)

array([  1, -20, -20])